### PR TITLE
French translation for the app

### PR DESCRIPTION
**Pull request by sivolc73**
Added french translation, checked in context in the app to make sure it makes sense in context and have a mostly uniform look, if the text all fit it should be good to go.

### CODE REVIEW

**Comment by curtishall** [comment]
Thank you for the PR @sivolc73 :)  It is under review.

P.S. - Are you using the desktop or mobile client?

**Review by alexmercerind — APPROVED** [review]
LGTM! Thanks for translations.

`flutter gen-l10n` _will tell the rest._

**Comment by sivolc73** [comment]
@curtishall I'm currently trying both for the first time, realized that the file mainly concern the mobile app I think? I would gladly help translate the desktop client more broadly I'm just really new to pull request and github in general. I'm considering bluecherry at my workplace, I installed a server on 30 days trial this week, so far so good!

**Comment by curtishall** [comment]
The translation file will be used for both mobile and desktop. 

When we have language updates I'll let you know. If you need a coupon for the iOS mobile app let me know and I'll send it to you.

chall@corp.bluecherry.net

**Review by bdlukaa — APPROVED** [review]
LGTM

**Pull request merged**
